project:
  type: website
  output-dir: docs

website:
  title: "Bill Perry's Website"
  site-url: "https://wlperry.github.io/ecostats_2026/"
  navbar:
    background: "#70131d"
    left:
      - text: "Bill's Homepage"
        href: "https://wlperry.github.io/index.html"
      - text: "Biostats Homepage"
        href: "https://wlperry.github.io/ecostats_2026/" # <-- FIXED LINK HERE
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/wlperry
      - icon: envelope
        href: mailto:wlperry@d.umn.edu
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=YVjQpRsAAAAJ&hl=en

format:
  html:
    theme: flatly
    css: styles.css        
    toc: true              
    toc-title: "On this page"