project:
  type: website
  output-dir: docs

website:
  title: "Bill Perry's Website"
  navbar:
    left:
      - text: "Bill's Homepage"
        href: "https://wlperry.github.io/index.html"
      - text: "Biostats Homepage"
        href: "https://wlperry.github.io/umd_biostats/"
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/wlperry
        aria-label: GitHub
      - icon: envelope
        href: mailto:wlperry@d.umn.edu
        aria-label: Email
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=YVjQpRsAAAAJ&hl=en
        aria-label: Google Scholar

format:
  html:
    css: styles.css        
    toc: true              
    toc-title: "On this page"