project:
  type: website
  output-dir: docs

website:
  title: "Bill Perry's Website"
  navbar:
    left:
      - text: "Bill's Homepage"
        href: "https://wlperry.github.io/index.html"
      - text: "Biostats Homepage"
        href: "https://wlperry.github.io/umd_biostats/"
      - text: "About"
        href: about.qmd
  # Optionally, add a footer or other settings here


format:
  html:
    theme: flatly         # You can experiment with other themes (e.g., cosmo, yeti)
    css: styles.css        # Reference your custom CSS file
    toc: true              # Enable a table of contents if your pages are long
    toc-title: "On this page"
    