project:
  type: website
  output-dir: docs

website:
  title: "Bill Perry's Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"  
        href: projects.qmd
      - text: "Fun"
        href: fun.qmd
    right:
      - text: "Bill's Homepage"
        href: "https://wlperry.github.io/index.html"
        target: "_blank"
      - text: "Biostats"
        href: "https://wlperry.github.io/umd_biostats/"
        target: "_blank"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: "On this page"